<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>LEGO Universe User Bug Report</title>
<style type="text/css">
body, td
{
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
}
.field
{
	margin-bottom: 12px;
	overflow: auto;
}
.field b
{
	display: block;
	line-height: 20px;
	width: 200px;
	float: left;
}
.hidden
{
	display: none;
}
.buttons
{
	border-top: 3px solid #e9e9e9;
	padding-top: 4px;
}
</style>

</head>

<body>
<form method="POST" name="_main" action="http://static.netdevil.com/dyn/lucrash.php">
	
<h1>LEGO Universe bug reporting form. Please help us improve the game by describing the bug.</h1>

<div class="field">
	<b>Username (optional):</b>
	<input type="text" name="username" size="30" value="" />
</div>
<div class="field">
	<b>Email Address (optional):</b>
	<input type="text" name="email_address" size="30" value="" />
</div>
<div class="field">
	<b>Description (optional):</b>
	<textarea name="description" rows="4" cols="30"></textarea>
</div>
<div class="field buttons">
	<input type="submit" name="submit" value="Send Report" />
</div>

All fields are optional. No personal or identifiable information will be included.
